import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import { SidebarItemAutogenerated } from '@docusaurus/plugin-content-docs/src/sidebars/types.js';

function auto(dirName: string): SidebarItemAutogenerated {
  return { type: 'autogenerated', dirName: dirName }
};

const Theory: SidebarsConfig = {
  dftBars: [auto('Theory/DFT')],
  basisBars: [auto('Theory/Basis')],
  ppBars: [auto('Theory/PP')],
  tddftBars: [auto('Theory/TDDFT')],
}

const Software: SidebarsConfig = {
  qeBars: [auto('Software/QE')],
}

const Dev: SidebarsConfig = {
  qeDevBars: [auto('Dev/QE')],
}

const sidebars: SidebarsConfig = {
  ...Theory,
  ...Software,
  ...Dev,
}

export default sidebars