import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import { SidebarItemAutogenerated } from '@docusaurus/plugin-content-docs/src/sidebars/types.js';

function auto(dirName: string): SidebarItemAutogenerated {
  return { type: 'autogenerated', dirName: dirName }
};

const Theory: SidebarsConfig = {
  dftBars: [auto('Theory/DFT')],
}

const Software: SidebarsConfig = {
  qeBars: [auto('Software/QE')],
  qeDevBars: [auto('Software/QE-Dev')],
}

const sidebars: SidebarsConfig = {
  ...Theory,
  ...Software,
}

export default sidebars